# Theme Settings Configuration File
##
### use settings.yml file for configure colors, ui, rtl, sidebar, animation options

settings:
  quick_colors: "" # select quick color schemes: "blue", "green", "orange", "pink", "purple", "red". If empty colors taken from _sass/ryancv/settings.scss
  dark_ui: 0 # activated dark ui styles
  rtl: 0 # activated rtl styles
  sidebar: 1 # for disable sidebar and sidebar button change to 0
  animation: "" # select animations for card sections: "horizontal", "rotate", "roll", "jack", "fade", "vertical"

background:
  capy1: "assets/img/bg-capys/capybara-standing-1.jpg"
  capy2: "assets/img/bg-capys/capybara-sitting-2.jpg"
  capy3: "assets/img/bg-capys/capybara-sitting-3.jpg"
  capy4: "assets/img/bg-capys/capybara-sitting-4.jpg"
  capy5: "assets/img/bg-capys/capybara-swimming-5.jpg"
  capy6: "assets/img/bg-capys/capybara-standing-6.jpg"
  capy7: "assets/img/bg-capys/capybara-sleeping-7.jpg"